### ISSUE TITLE
Não estou consegui baixar de uma plataforma

### ISSUE THREAD

**Issue by guilhermelirio** [Jose-Borges-Dev/Pandavideo-Downloader#1]
Boa tarde @Jose-Borges-Dev !

Está dando um erro quando tenta baixar um vídeo de uma plataforma:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vz-0b5ac5ee-df6.cdn1.pandavideo.com', port=443): Max retries exceeded with url: /2353144b-db73-4955-8b0a-c03ffbf4b825/1280x720/video.m3u8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024778A5C520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

Talvez eu não entendi direito como fazer o download.

Consegue me ajudar?

**Comment by borges-z** [comment]
Que estranho, nunca tinha visto esse erro.

Mas vou deixar aqui um vídeo de demonstração de como executar: [Demonstração](https://drive.google.com/file/d/1L360hwzHsYWmAJu7aO_D10zHYcoTNfyr/view?usp=share_link)

qualquer coisa escreva aqui, ficarei feliz em ajudar :)

**Comment by guilhermelirio** [comment]
Então, eu tentei dessa mesma forma e deu esse erro informado.

Eu fiz umas edições aqui no script e consegui baixar para mim (sei só o básico do Python kk)

Os dados que usei foram:
```
https://b-vz-0b5ac5ee-df6.tv.pandavideo.com.br/3f100a65-5b02-495e-8ae8-cfb00047d5e7/playlist.m3u8
https://assista.escalaxz.com.br/
```

E eu tive que forçar ele a pegar o 1920x1080, sempre pegava em HD (720p).

**Comment by borges-z** [comment]
Interessante @guilhermelirio!

Fiz um commit consertando esse bug e adicionado a escolha para escolher as resoluções disponíveis, aqui para mim deu tudo certo segundo meus vários testes.

Nos meus testes passados eu não tinha visto esse domínio `b-cdn.net`, por isso que o script dava erro, ele mandava o request para o endereço padrão e não estava obtendo nenhuma resposta. Bom... agora eu tratei isso e vamos lá :)

Da um git pull e testa ai.

**Comment by guilhermelirio** [comment]
@Jose-Borges-Dev irei testar hoje e te dou um feedback!

Obrigado!

**Comment by guilhermelirio** [comment]
@Jose-Borges-Dev está funcionando perfeitamente!

Muito obrigado!
