### ISSUE TITLE
Erro ao tentar baixar pelo Astronmembers

### ISSUE THREAD

**Issue by Dalvani** [Jose-Borges-Dev/Pandavideo-Downloader#2]
Bom dia, não consigo baixar do pandavideo qdo entro pela plataforma do Astronmembers.
playlist: https://b-vz-66f9f3a1-94a.tv.pandavideo.com.br/dbb426b2-d7df-4625-80c2-9b1aed79791e/playlist.m3u8
plataforma: https://imersaobaixistamet.astronmembers.com/

Após selecionar a resolução, nada acontece. Analisando o retorno que recebo vi a seguinte mensagem "403 Forbidden".

Cabeçalho de resposta exibido no browser para o link da resolução 1280x720:
:authority: b-vz-66f9f3a1-94a.tv.pandavideo.com.br
:method: GET
:path: /dbb426b2-d7df-4625-80c2-9b1aed79791e/1280x720/video.m3u8
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: pt-BR,pt;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
cache-control: no-cache
origin: https://player-vz-66f9f3a1-94a.tv.pandavideo.com.br
pragma: no-cache
referer: https://player-vz-66f9f3a1-94a.tv.pandavideo.com.br/
sec-ch-ua: "Microsoft Edge";v="111", "Not(A:Brand";v="8", "Chromium";v="111"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62

Consegue me ajudar? Grato

**Comment by borges-z** [comment]
Olá @Dalvani, desculpa a demora, o github não me notificou por e-mail.

Mas analisei a comunicação e foi mudado algumas coisas para o astronmembers.com, e agradeço por postar várias partes da comunicação, isso ajuda demais!

logo logo eu solto um commit

**Comment by Dalvani** [comment]
Obrigado José, desculpa pela demora no retorno. 
Fiz o teste, baixou alguns arquivos e outros ficaram com erros. 
Analisando o código vi um erro na linha 128. O código troca todas as letras "n" por nada e isso causa erros nos tokens que possuem a letra "n", logo não baixando o arquivo.

Minha solução foi: 
1 - Mudei a linha 128 conforme abaixo 
 i = i.replace("nhttps", "https")
2 - Comentar ou remover a linha 149

Favor ajustar seu código.

att,
